-- MySQL Script generated by MySQL Workbench
-- Thu Nov 13 19:54:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kosten
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kosten
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kosten` DEFAULT CHARACTER SET utf8 ;
USE `kosten` ;

-- -----------------------------------------------------
-- Table `kosten`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`rol` ;

CREATE TABLE IF NOT EXISTS `kosten`.`rol` (
  `idRol` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`sector` ;

CREATE TABLE IF NOT EXISTS `kosten`.`sector` (
  `idSector` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `nomenclatura` VARCHAR(10) NULL,
  PRIMARY KEY (`idSector`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`estadoU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`estadoU` ;

CREATE TABLE IF NOT EXISTS `kosten`.`estadoU` (
  `idEstadoU` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idEstadoU`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`cargo` ;

CREATE TABLE IF NOT EXISTS `kosten`.`cargo` (
  `idCargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idCargo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`usuario` ;

CREATE TABLE IF NOT EXISTS `kosten`.`usuario` (
  `idUsuario` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni` INT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `legajo` VARCHAR(45) NOT NULL,
  `rol_idRol` INT UNSIGNED NOT NULL,
  `sector_idSector` INT UNSIGNED NOT NULL,
  `estadoU_idEstadoU` INT UNSIGNED NOT NULL,
  `cargo_idCargo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_user_tipoUser_idx` (`rol_idRol` ASC) ,
  INDEX `fk_user_sector_idx` (`sector_idSector` ASC) ,
  INDEX `fk_usuario_estadoU_idx` (`estadoU_idEstadoU` ASC) ,
  INDEX `fk_usuario_cargo_idx` (`cargo_idCargo` ASC) ,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `legajo_UNIQUE` (`legajo` ASC) ,
  CONSTRAINT `fk_user_tipoUser`
    FOREIGN KEY (`rol_idRol`)
    REFERENCES `kosten`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_sector`
    FOREIGN KEY (`sector_idSector`)
    REFERENCES `kosten`.`sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_estadoU`
    FOREIGN KEY (`estadoU_idEstadoU`)
    REFERENCES `kosten`.`estadoU` (`idEstadoU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_cargo`
    FOREIGN KEY (`cargo_idCargo`)
    REFERENCES `kosten`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);



-- -----------------------------------------------------
-- Table `kosten`.`tipoDocumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`tipoDocumento` ;

CREATE TABLE IF NOT EXISTS `kosten`.`tipoDocumento` (
  `idTipoDocumento` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `nomenclatura` VARCHAR(10) NOT NULL,
  `icono` VARCHAR(30) NULL,
  PRIMARY KEY (`idTipoDocumento`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`estado` ;

CREATE TABLE IF NOT EXISTS `kosten`.`estado` (
  `idEstado` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`unidadEjecutora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`unidadEjecutora` ;

CREATE TABLE IF NOT EXISTS `kosten`.`unidadEjecutora` (
  `idUnidadEjecutora` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nomenclatura` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUnidadEjecutora`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`documento` ;

CREATE TABLE IF NOT EXISTS `kosten`.`documento` (
  `idDocumento` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(300) NOT NULL,
  `resumen` VARCHAR(600) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `numDocumento` varchar(45) NOT NULL,
  `activo` boolean NOT NULL,
  `tipoDocumento_idTipoDocumento` INT UNSIGNED NOT NULL,
  `estado_idestado` INT UNSIGNED NOT NULL,
  `sector_idSector` INT UNSIGNED NOT NULL,
  `unidadEjecutora_idUnidadEjecutora` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idDocumento`),
  INDEX `fk_documento_tipoDocumento_idx` (`tipoDocumento_idTipoDocumento` ASC) ,
  INDEX `fk_documento_estado_idx` (`estado_idestado` ASC) ,
  INDEX `fk_documento_sector_idx` (`sector_idSector` ASC) ,
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC) ,
  UNIQUE INDEX `numDocumento_UNIQUE` (`numDocumento` ASC) ,
  INDEX `idx_fechaCreacion` (`fechaCreacion` ASC),
  CONSTRAINT `fk_documento_unidadEjecutora`
  FOREIGN KEY (`unidadEjecutora_idUnidadEjecutora`)
  REFERENCES `kosten`.`unidadEjecutora` (`idUnidadEjecutora`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_tipoDocumento`
    FOREIGN KEY (`tipoDocumento_idTipoDocumento`)
    REFERENCES `kosten`.`tipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_estado`
    FOREIGN KEY (`estado_idestado`)
    REFERENCES `kosten`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_sector`
    FOREIGN KEY (`sector_idSector`)
    REFERENCES `kosten`.`sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `kosten`.`registro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`registro` ;

CREATE TABLE IF NOT EXISTS `kosten`.`registro` (
  `idRegistro` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fechaCarga` DATE NULL,
  `tipoOperacion` VARCHAR(45) NOT NULL,
  `usuarioResponsable_idUsuario` BIGINT(20) UNSIGNED NOT NULL,
  `documentoAfectado_idDocumento` BIGINT(20) UNSIGNED NULL,
  `usuarioAfectado_idUsuario` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`idRegistro`),
-- Índices para mejorar la búsqueda y gestión de las FK
  INDEX `idx_fechaCarga` (`fechaCarga` ASC),
  INDEX `fk_registro_responsable_idx` (`usuarioResponsable_idUsuario` ASC),
  INDEX `fk_registro_documento_afectado_idx` (`documentoAfectado_idDocumento` ASC),
  INDEX `fk_registro_usuario_afectado_idx` (`usuarioAfectado_idUsuario` ASC),
-- FK para el Usuario que realizó la acción
  CONSTRAINT `fk_registro_usuario_responsable`
    FOREIGN KEY (`usuarioResponsable_idUsuario`)
    REFERENCES `kosten`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
-- FK para el Documento Afectado
  CONSTRAINT `fk_registro_documento_afectado`
    FOREIGN KEY (`documentoAfectado_idDocumento`)
    REFERENCES `kosten`.`documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
-- FK para el Usuario Afectado
  CONSTRAINT `fk_registro_usuario_afectado`
    FOREIGN KEY (`usuarioAfectado_idUsuario`)
    REFERENCES `kosten`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`palabraClave`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`palabraClave` ;

CREATE TABLE IF NOT EXISTS `kosten`.`palabraClave` (
  `idPalabraClave` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idPalabraClave`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`archivo` ;

CREATE TABLE IF NOT EXISTS `kosten`.`archivo` (
  `idArchivo` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `documento_idDocumento` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`idArchivo`),
  INDEX `fk_archivo_documento_idx` (`documento_idDocumento` ASC) ,
  CONSTRAINT `fk_archivo_documento`
    FOREIGN KEY (`documento_idDocumento`)
    REFERENCES `kosten`.`documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`etiqueta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`etiqueta` ;

CREATE TABLE IF NOT EXISTS `kosten`.`etiqueta` (
  `documento_idDocumento` BIGINT(20) UNSIGNED NOT NULL,
  `palabraClave_idPalabraClave` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `fk_etiqueta_palabraClave_idx` (`palabraClave_idPalabraClave` ASC) ,
  PRIMARY KEY (`documento_idDocumento`, `palabraClave_idPalabraClave`),
  CONSTRAINT `fk_etiqueta_documento`
    FOREIGN KEY (`documento_idDocumento`)
    REFERENCES `kosten`.`documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiqueta_palabraClave`
    FOREIGN KEY (`palabraClave_idPalabraClave`)
    REFERENCES `kosten`.`palabraClave` (`idPalabraClave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `kosten`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`permiso` ;

CREATE TABLE IF NOT EXISTS `kosten`.`permiso` (
  `idpermiso` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idpermiso`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`asigna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`asigna` ;

CREATE TABLE IF NOT EXISTS `kosten`.`asigna` (
  `rol_idRol` INT UNSIGNED NOT NULL,
  `permiso_idpermiso` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rol_idRol`, `permiso_idpermiso`),
  INDEX `fk_asigna_permiso_idx` (`permiso_idpermiso` ASC) ,
  CONSTRAINT `fk_asigna_rol`
    FOREIGN KEY (`rol_idRol`)
    REFERENCES `kosten`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asigna_permiso`
    FOREIGN KEY (`permiso_idpermiso`)
    REFERENCES `kosten`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kosten`.`referencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kosten`.`referencia` ;

CREATE TABLE IF NOT EXISTS `kosten`.`referencia` (
  `documento_idDocumentoOrigen` BIGINT(20) UNSIGNED NOT NULL,
  `documento_idDocumentoReferencial` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`documento_idDocumentoOrigen`, `documento_idDocumentoReferencial`),
  INDEX `fk_referencia_documento_referencial_idx` (`documento_idDocumentoReferencial` ASC) , 
  CONSTRAINT `fk_referencia_documento_origen`
    FOREIGN KEY (`documento_idDocumentoOrigen`)
    REFERENCES `kosten`.`documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_referencia_documento_referencial`
    FOREIGN KEY (`documento_idDocumentoReferencial`)
    REFERENCES `kosten`.`documento` (`idDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
